### ISSUE TITLE
Peer to peer code review

### ISSUE THREAD

**Issue by adeola003** [Lul-Abdifan/Awesome-Book#2]
# Review comments ♻️ 
Hello Abdi, 👋🏾 Good job on the Awesome books project so far. However, we as your morning session team noted a few issues that we feel need to be looked at and responded to. 
#### They include: 
- Removing the unnecessary code from the initial loading function *(Page.retrieveToPage();)*;
- Adding hover effects on the add button. 😄

**Comment by Lul-Abdifan** [comment]
@adeola003 @Bennyjoez @fickryiman
Hello, My Morning Meeting Group.                                                                                                                                               Your thoughtful insights and constructive feedback have been instrumental in making to do more
 Thank you for all. I have done it. :smile: :man_technologist: 

:smile: :+1: Happy Coding :smile:

**Comment by Bennyjoez** [comment]
Wonderful 🎊 
<img src="https://media0.giphy.com/media/cOvgh3VjLmeg8LLBtk/giphy-downsized-medium.gif"/>
